name: SecretBlock
main: io.github.Andi489156.SecretBlock.SecretBlock
version: 1.0.0
author: Andi489156

commands:
  sb:
    description: Use to get information about all commands of SecretBlock.
    usage: |
      Secret Block Commands:
      /sb savelocation
      /sb create [controller, teleporter]
      /sb edit controller
      /sb adduser <player>
    permission: SecretBlock.use
    permission-message: You don't have the permission for that command. You really suck, man.