name: SecretBlock
main: io.github.Andi489156.SecretBlock.SecretBlock
version: 1.0
author: Andi489156

commands:
  sb:
    description: Use to get information about all commands of SecretBlock.
    usage: |
      /sb 
      /sb savelocation
      /sb create controller
      /sb create teleporter
      /sb edit controller
    permission: TestPlugin.test
    permission-message: You don't have the permission to test this.